{{- range $networkPolicy := .Values.networkPolicy }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $networkPolicy.name }}
  namespace: {{ $networkPolicy.namespace }}
spec:
  podSelector:
    matchLabels:
      app: {{ $networkPolicy.podSelector.matchLabels.app }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - ports:
    - port: {{ $networkPolicy.ingress.ports.port }}
{{- end}}
