{{- range $app := .Values.service }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $app.name }}
  namespace: {{ $app.namespace }}
spec:
  type: {{ $app.type }}
  ports:
    - port: {{ $app.port }}
      targetPort: {{ $app.targetPort }}
  selector:
    app: {{ $app.app }}
{{- end}}

