name: Python application

on:
  push:
    branches: ["app-code"]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: housseinhmila/kube-argo:app-${{ github.run_number }}
  update-config:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: changing the deployment of git repo
        with:
          repository: 'HousseinHmila/Kube-UP'
          ref: 't-007'
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: modify the image
        run: |
          git config user.email housseinhmila@gmail.com
          git config user.name Houssein
          pwd
          cat ./helm/values.yaml
          pwd
          sed -i "s+housseinhmila/kube-argo.*+housseinhmila/kube-argo:app-$RUN_NUMBER+g" ./helm/values.yaml
          cat ./helm/values.yaml
          git add .
          git commit -m 'Done  by Github Actions   Job changemanifest: ${{ github.run_number }}'
          git push origin t-007
        env:
            GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
            RUN_NUMBER: ${{ github.run_number }}
